version: '3'

services:

  db:
    container_name: aries_mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    tty: true
    environment:
      MYSQL_DATABASE: aries
      MYSQL_ROOT_PASSWORD: root_119J6uMKlCD
      MYSQL_PASSWORD: aries_6xz888!YfQ
      MYSQL_USER: aries
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./db:/var/lib/mysql

networks:
  aries-treine:
    driver: bridge

